### ISSUE TITLE
Configure doesn't work

### ISSUE THREAD

**Issue by mdotmoment11** [flightaware/yajl-tcl#20]
/home/brad/yajl-tcl# ./configure
-su: ./configure: No such file or directory

**Comment by bovine** [comment]
We don't commit the generated configure scripts, but if you have the autoconf tools installed you can just run "autoreconf" first.

**Comment by mdotmoment11** [comment]
Yep. Figured that out. Thanks

**Comment by bovine** [comment]
I've clarified the documentation.
fixed by commit 20884eb768a09a472a825903d57420b11461d516
