### ISSUE TITLE
Add map_json

### ISSUE THREAD

**Issue by bradynapier** [flightaware/yajl-tcl#21]
Hey There,
  Thanks so much for this package, I use it every day of my life pretty much!  One thing that might be nice to add to this package is an official means of doing "raw" or "map_json" when already formatted jsonshould be added to what you are working on.

  I am using number to achieve it now, and it's no big deal but would be nice to either add a note in the documentation or have some sort of official means of handling this scenario.

     proc formatRequest {identity method path messageBody} {
         set json [yajl create #auto]
	     $json map_open \
	         string "identity" string $identity                              \
	         string "requests" array_open                                    \
	        map_open                                                    \
	            string "uuid" string $::URC::Controller                 \
	            string "method" string $method                          \
	            string "path" string $path                              \
	            string "dataFormat" string "json"                       \
	            string "messageBody" number $messageBody                \
	            map_close                                                   \
             array_close                                                     \
         map_close                                                           
	  set body [$json get]
	  $json delete
	  return $body

     }

Resulting in:

     {"identity":"1","requests":[{"uuid":"4","method":"2","path":"3","dataFormat":"json","messageBody":{"systemID":"4","key":"myKey"}}]}

**Comment by bradennapier** [comment]
just ran into this again where the need to add already generate json arises... in this case when the data includes the key - the number trick doesnt work here

**Comment by bovine** [comment]
Unfortunately, the underlying yajl library does not really expose the ability to directly inject raw JSON into the accumulated output without further escaping. The typical usecase is specifically to want yajl to do escaping of the different data types for you, and prevent the possibility of even being able to output invalid JSON.  Here is the documentation of the YAJL generation functions that yajltcl exposes: https://lloyd.github.io/yajl/yajl-2.1.0/yajl__gen_8h.html

One other option that you might consider is to re-parse the raw JSON that you have and then emit that back into the yajltcl object that you are generating. There will be a little bit of a performance hit from having to parse and then emit it again, but it validates your content and works with the existing interface:

```Tcl
 proc formatRequest {identity method path messageBody} {
     set json [yajl create #auto]
     set parsedMessageBody [yajl parse $messageBody]
     $json map_open \
         string "identity" string $identity                              \
         string "requests" array_open                                    \
        map_open                                                    \
            string "uuid" string $::URC::Controller                 \
            string "method" string $method                          \
            string "path" string $path                              \
            string "dataFormat" string "json"                       \
            string "messageBody" {*}$parsedMessageBody                \
            map_close                                                   \
         array_close                                                     \
     map_close                                                           
  set body [$json get]
  $json delete
  return $body
 }
```

If your messageBody contains the key name, then you can omit the ```string "messageBody" ``` part from the above.

**Comment by bradennapier** [comment]
Ok thanks!
