### ISSUE TITLE
Atom Editor / Syntax Highlighting

### ISSUE THREAD

**Issue by bradennapier** [flightaware/yajl-tcl#25]
Just wanted to let you know that the language grammar that I have been working on for Atom Editor (and technically Sublime) will support highlighting for yajl-tcl!  Love this package, thanks a ton!  Wish we had a combination of this and rl_json in one (rl_json is a bit faster but it is not good at dynamic values / building up values).

![image](https://user-images.githubusercontent.com/15365418/29538600-5b461054-867b-11e7-8079-564a10b5bd27.png)

For best results, it does require to use the undocumented map_key rather than "string" when mapping each key although it just highlights as as a string if map_key isn't used so not a big deal.

![image](https://user-images.githubusercontent.com/15365418/29538743-f708a1aa-867b-11e7-8d51-69bc780ebd26.png)

It is available in atom editor as "language-dashtcl" although these updates aren't uploaded yet as of writing this.

Anyway, definitely makes it a bit nicer to read and work with so thought I would share!

**Comment by bovine** [comment]
That's nice work. Thanks for letting us know about it!
