### ISSUE TITLE
[$obj parse] not working properly?

### ISSUE THREAD

**Issue by bradennapier** [flightaware/yajl-tcl#27]
Ok so moving my code base over to not using the [number] work around i discuss in #21 and i am getting errors that make zero sense

```tcl
set json [yajl create #auto]
set parsed [$json parse {{"persist":1}}]
```

```
parse error: trailing garbage
                                        {"persist":1}
                     (right here) ------^
```

**Comment by bradennapier** [comment]
Once this happens it actually breaks the object forever as well.

**Comment by resuna** [comment]
It seems to be picky about spaces:

```
% $json parse {"persist":1}
parse error: trailing garbage
                              "persist":1
                     (right here) ------^
% $json reset
% $json parse {{"persist": 1}}
map_open map_key persist number 1 map_close
```

**Comment by bovine** [comment]
I don't think using the same object simultaneously for parsing and generation activities is really a use-case that was intended. I haven't looked deep enough to determine if it is feasible to make work as you intend yet, but at the moment I'd probably lean towards making any of the "parse" methods generate an error if it is still being used for generation without an intervening "reset".

**Comment by bradennapier** [comment]
I mean if that is the case, it kind of backs up the concept of making the [parse] command a static method and removing it from the object all together - otherwise it simply creates confusion and conflicts since they are 100% different at that point if they are not ever meant to be used together without breaking each other.

**Comment by bovine** [comment]
It cannot be easily static for the previously stated reasons of needing to store substantial state and callbacks data during the process of the parse. If you need to do two unrelated operations simultaneously, then you need to create two separate objects.

**Comment by bovine** [comment]
If you would just like a cleaner syntax for quickly parsing snippets, you could of course create a helper proc:

    proc yajl_parse {json} {
        set object [yajl create #auto]
        set parsed [$object parse $json]
        $object delete
        return $parsed
    }

**Comment by bovine** [comment]
The above example probably needs a `catch` to handle errors during the parse, in order to avoid leaking the object without deleting it.

**Comment by bradennapier** [comment]
I ended with the following: https://github.com/Dash-OS/tcl-modules/blob/master/json_tools-1.3.0.tm#L412-L420

try/catch is the responsibility in this case of the caller since that is a lib.  Since it is using a single object in this case it ends up working well - let me knwo fi there is a problem with my logic there but it appears to work.
