### ISSUE TITLE
What is the current stable version?

### ISSUE THREAD

**Issue by nextensible** [flightaware/yajl-tcl#34]

**Comment by bovine** [comment]
Just look at the last tagged release
https://github.com/flightaware/yajl-tcl/releases

There are some more changes in master branch that haven't been released yet though.

**Comment by bovine** [comment]
I've tagged a v1.7.0-rc1 release candidate if you want something a little more bleeding edge.

**Comment by nextensible** [comment]
Okay, thanks a lot. I was just unsure, because the start page suggests something different by saying "Version 1.7.0" directly below the headline. This should be either removed, or replaced by the typical "Current stable release: ... Current development version: ..." or something similar.
