### ISSUE TITLE
Issues while processing json containing braces

### ISSUE THREAD

**Issue by ramikhaldi** [flightaware/yajl-tcl#40]
Hi,

We encoutered an error while trying to convert a json containing braces:

`::yajl::json2dict { {"Comment": "ac\{db"} }`

Result: 

`lexical error: inside a string, '\' occurs before a character which it may not.
                        {"Comment": "ac\{db"}
                     (right here) ------^`

Also escaping the baces like: ` ::yajl::json2dict { {"Comment": "ac\\{db"} }` does not help..

Any ideas or hints on that ?

Thanks in Advance

KR,
Rami

**Comment by resuna** [comment]
Unfortunately, a JSON string is not a kind of extended Tcl list. MOST of the time it's safe to do so, but not always. Really, it's a string, and sometimes you just have  to go all the way and quote it as a string.

::yajl::json2dict "{\"Comment\": \"ac{db\"}"

**Comment by ramikhaldi** [comment]
The escaped quotes in the key _comment_ were just required because of the brace. Unfortunately this workaround does not help much, as it requires that the caller normalize the Json input prior to calling the library function. That could lead to other issues.

**Comment by resuna** [comment]
It is not possible to create a Tcl string containing unbalanced unescaped curly braces if it's delimited in curly braces. You have to use quotes or full escapes. This is purely a matter of expressing the string in Tcl source code. It doesn't involve normalizing json nor does it effect json produced computationally or read from a socket or file.

It's like how if you want to `puts` a single curly brace, you can't do this:

```
% puts {\{}
\{
```
You have to do this:

```
% puts "{"
{
```

Or this:

```
% puts \{
{
```

**Comment by resuna** [comment]
You could also use \u UTF escaping for the brace.

**Comment by ramikhaldi** [comment]
@resuna Thanks for your comments.
